# ruff: noqa: D100, D101
from enum import Enum


class ErrorCode(str, Enum):
    # NETWORK
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    NETWORK_REQUEST_FAILED = "NETWORK_REQUEST_FAILED"

    # API
    API_BAD_REQUEST = "API_BAD_REQUEST"
    API_UNAUTHORIZED = "API_UNAUTHORIZED"
    API_SERVER_ERROR = "API_SERVER_ERROR"
    API_INVALID_RESPONSE = "API_INVALID_RESPONSE"
    API_FORBIDDEN = "API_FORBIDDEN"
    API_NOT_FOUND = "API_NOT_FOUND"
    API_RATE_LIMITED = "API_RATE_LIMITED"

    # CHARGE
    CHARGE_FAILED = "CHARGE_FAILED"
    CHARGE_DECLINED = "CHARGE_DECLINED"
    CHARGE_RESPONSE_INVALID = "CHARGE_RESPONSE_INVALID"

    # VALIDATION
    VALIDATION_FAILED = "VALIDATION_FAILED"
    VALIDATION_INVALID_OTP = "VALIDATION_INVALID_OTP"

    # VERIFY
    VERIFY_FAILED = "VERIFY_FAILED"
    VERIFY_STATUS_MISMATCH = "VERIFY_STATUS_MISMATCH"

    # IDENTITY
    IDENTITY_FETCH_FAILED = "IDENTITY_FETCH_FAILED"
    IDENTITY_APP_ID_NOT_FOUND = "IDENTITY_APP_ID_NOT_FOUND"

    # SDK
    SDK_JSON_PARSE_ERROR = "SDK_JSON_PARSE_ERROR"
    SDK_INVALID_ARGUMENT = "SDK_INVALID_ARGUMENT"

    # CONFIG
    CONFIG_MISSING_KEY = "CONFIG_MISSING_KEY"


# Module-level — outside the enum class
HTTP_ERROR_MAP: dict[int, ErrorCode] = {
    400: ErrorCode.API_BAD_REQUEST,
    401: ErrorCode.API_UNAUTHORIZED,
    403: ErrorCode.API_FORBIDDEN,
    404: ErrorCode.API_NOT_FOUND,
    429: ErrorCode.API_RATE_LIMITED,
}
