name: Review changes on Dev (Commits/PRs)

on:
  push:
    branches: ['dev']
  pull_request:
    types:
      - opened

jobs:
  code-check:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.7'
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    

    - name: Checkmarx One ClI Action
      uses: checkmarx/ast-github-action@main
      with:
        project_name: Github Projects
        cx_tenant: Flutterwave
        base_uri: https://eu.ast.checkmarx.net/
        cx_client_id: ${{ secrets.CX_CLIENT_ID }}
        cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}

    - name: setup python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        
    - name: install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run unit tests and coverage scan
      env:
        PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
      run: |
        pip install coverage
        coverage run test.py

    - name: upload coverage report to codecov
      uses: codecov/codecov-action@v2

    - name: push build status to slack
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
